# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/connor/Documents/Programs/Vivado/4300/SHA-256-SoC/debug_hw/debug_hw.srcs/sources_1/bd/debug_cpu_v2/ip/debug_cpu_v2_mdm_0_0/debug_cpu_v2_mdm_0_0.xci
# IP: The module: 'debug_cpu_v2_mdm_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/connor/Documents/Programs/Vivado/4300/SHA-256-SoC/debug_hw/debug_hw.srcs/sources_1/bd/debug_cpu_v2/ip/debug_cpu_v2_mdm_0_0/debug_cpu_v2_mdm_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_cpu_v2_mdm_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/connor/Documents/Programs/Vivado/4300/SHA-256-SoC/debug_hw/debug_hw.srcs/sources_1/bd/debug_cpu_v2/ip/debug_cpu_v2_mdm_0_0/debug_cpu_v2_mdm_0_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_cpu_v2_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/connor/Documents/Programs/Vivado/4300/SHA-256-SoC/debug_hw/debug_hw.srcs/sources_1/bd/debug_cpu_v2/ip/debug_cpu_v2_mdm_0_0/debug_cpu_v2_mdm_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_cpu_v2_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/connor/Documents/Programs/Vivado/4300/SHA-256-SoC/debug_hw/debug_hw.srcs/sources_1/bd/debug_cpu_v2/ip/debug_cpu_v2_mdm_0_0/debug_cpu_v2_mdm_0_0.xci
# IP: The module: 'debug_cpu_v2_mdm_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/connor/Documents/Programs/Vivado/4300/SHA-256-SoC/debug_hw/debug_hw.srcs/sources_1/bd/debug_cpu_v2/ip/debug_cpu_v2_mdm_0_0/debug_cpu_v2_mdm_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_cpu_v2_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/connor/Documents/Programs/Vivado/4300/SHA-256-SoC/debug_hw/debug_hw.srcs/sources_1/bd/debug_cpu_v2/ip/debug_cpu_v2_mdm_0_0/debug_cpu_v2_mdm_0_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_cpu_v2_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/connor/Documents/Programs/Vivado/4300/SHA-256-SoC/debug_hw/debug_hw.srcs/sources_1/bd/debug_cpu_v2/ip/debug_cpu_v2_mdm_0_0/debug_cpu_v2_mdm_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_cpu_v2_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
