# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Vivado/Nexys4DDR_Master.xdc

# Block Designs: bd/axi_cpu/axi_cpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu || ORIG_REF_NAME==axi_cpu} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_microblaze_0_0/axi_cpu_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_microblaze_0_0 || ORIG_REF_NAME==axi_cpu_microblaze_0_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_dlmb_v10_0/axi_cpu_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_dlmb_v10_0 || ORIG_REF_NAME==axi_cpu_dlmb_v10_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_ilmb_v10_0/axi_cpu_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_ilmb_v10_0 || ORIG_REF_NAME==axi_cpu_ilmb_v10_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_dlmb_bram_if_cntlr_0/axi_cpu_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_cpu_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_ilmb_bram_if_cntlr_0/axi_cpu_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_cpu_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_lmb_bram_0/axi_cpu_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_lmb_bram_0 || ORIG_REF_NAME==axi_cpu_lmb_bram_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_mdm_1_0/axi_cpu_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_mdm_1_0 || ORIG_REF_NAME==axi_cpu_mdm_1_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_clk_wiz_1_0/axi_cpu_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_clk_wiz_1_0 || ORIG_REF_NAME==axi_cpu_clk_wiz_1_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_rst_clk_wiz_1_100M_0/axi_cpu_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_cpu_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_xbar_0/axi_cpu_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_xbar_0 || ORIG_REF_NAME==axi_cpu_xbar_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_axi_interconnect_0_0/axi_cpu_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_axi_interconnect_0_0 || ORIG_REF_NAME==axi_cpu_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_axi_timer_0_0/axi_cpu_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_axi_timer_0_0 || ORIG_REF_NAME==axi_cpu_axi_timer_0_0} -quiet] -quiet

# IP: bd/axi_cpu/ip/axi_cpu_axi_uartlite_0_0/axi_cpu_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_cpu_axi_uartlite_0_0 || ORIG_REF_NAME==axi_cpu_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_microblaze_0_0/axi_cpu_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_microblaze_0_0 || ORIG_REF_NAME==axi_cpu_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_microblaze_0_0/axi_cpu_microblaze_0_0_ooc_debug.xdc

# XDC: bd/axi_cpu/ip/axi_cpu_dlmb_v10_0/axi_cpu_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_dlmb_v10_0 || ORIG_REF_NAME==axi_cpu_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_ilmb_v10_0/axi_cpu_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_ilmb_v10_0 || ORIG_REF_NAME==axi_cpu_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_lmb_bram_0/axi_cpu_lmb_bram_0_ooc.xdc

# XDC: bd/axi_cpu/ip/axi_cpu_mdm_1_0/axi_cpu_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_mdm_1_0 || ORIG_REF_NAME==axi_cpu_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_mdm_1_0/axi_cpu_mdm_1_0_ooc_trace.xdc

# XDC: bd/axi_cpu/ip/axi_cpu_clk_wiz_1_0/axi_cpu_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_clk_wiz_1_0 || ORIG_REF_NAME==axi_cpu_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_clk_wiz_1_0/axi_cpu_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_clk_wiz_1_0 || ORIG_REF_NAME==axi_cpu_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_clk_wiz_1_0/axi_cpu_clk_wiz_1_0_ooc.xdc

# XDC: bd/axi_cpu/ip/axi_cpu_rst_clk_wiz_1_100M_0/axi_cpu_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_cpu_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_rst_clk_wiz_1_100M_0/axi_cpu_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_cpu_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_axi_timer_0_0/axi_cpu_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_axi_timer_0_0 || ORIG_REF_NAME==axi_cpu_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_axi_timer_0_0/axi_cpu_axi_timer_0_0_ooc.xdc

# XDC: bd/axi_cpu/ip/axi_cpu_axi_uartlite_0_0/axi_cpu_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_axi_uartlite_0_0 || ORIG_REF_NAME==axi_cpu_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/ip/axi_cpu_axi_uartlite_0_0/axi_cpu_axi_uartlite_0_0_ooc.xdc

# XDC: bd/axi_cpu/ip/axi_cpu_axi_uartlite_0_0/axi_cpu_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_cpu_axi_uartlite_0_0 || ORIG_REF_NAME==axi_cpu_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/axi_cpu/axi_cpu_ooc.xdc
